### ISSUE TITLE
Can't Display GitHub Profile Image

### ISSUE THREAD

**Issue by kiliczsh** [rapidpages/rapidpages#15]
I think srcset paths are not valid

<img width="1275" alt="Screenshot 2023-09-26 at 20 25 49" src="https://github.com/rapidpages/rapidpages/assets/3473393/65aa1a97-e4e9-4d6d-892d-a37179a6ebce">

**Comment by muratsu** [comment]
Fixed by #[25d0761](https://github.com/rapidpages/rapidpages/commit/25d0761498eb863d399e74a0fac5bb8b7da4f9db)
